[plotly-artifacts]
git-tree-sha1 = "fa6f0cc6fbf362f756ea495f68bd56119747541a"

    [[plotly-artifacts.download]]
    sha256 = "7f963bebbd8d15d5a2dd1ef69b7e55a1e6f53ffe1adc8fc69cd489b477a6a93a"
    url = "https://github.com/yiyuezhuo/PlotlyJS.jl/releases/download/0.14.1/plotly.js-artifacts.tar.gz"
